# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XCz_93SWYf4HY_QUd0VgfwbIB0_n9rLg
"""

import pandas as pd

def read_file(file_name, columns, seperator, headerNum = 0, hasHeader=False):
  excel = pd.read_csv( file_name, seperator, header = headerNum ) if hasHeader else pd.read_csv( file_name, seperator, header=None )
  return pd.DataFrame(excel, columns = columns ) if hasHeader else pd.DataFrame(excel)